ALTER TABLE events
  ADD COLUMN IF NOT EXISTS location TEXT,
  ADD COLUMN IF NOT EXISTS is_all_day BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS recurrence VARCHAR(50),
  ADD COLUMN IF NOT EXISTS recurrence_end_date TIMESTAMP,
  ADD COLUMN IF NOT EXISTS reminder INTEGER,
  ADD COLUMN IF NOT EXISTS second_reminder INTEGER,
  ADD COLUMN IF NOT EXISTS color VARCHAR(20),
  ADD COLUMN IF NOT EXISTS category VARCHAR(50),
  ADD COLUMN IF NOT EXISTS priority VARCHAR(20) DEFAULT 'medium',
  ADD COLUMN IF NOT EXISTS url TEXT,
  ADD COLUMN IF NOT EXISTS notes TEXT,
  ADD COLUMN IF NOT EXISTS travel_time INTEGER,
  ADD COLUMN IF NOT EXISTS video_call_link TEXT,
  ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT 'confirmed';

GRANT ALL PRIVILEGES ON TABLE events TO family_admin;
GRANT USAGE, SELECT ON SEQUENCE events_id_seq TO family_admin;