ALTER TABLE tasks ADD COLUMN is_standalone BOOLEAN DEFAULT false;
ALTER TABLE tasks ADD COLUMN due_date TIMESTAMP;

GRANT ALL PRIVILEGES ON TABLE tasks TO family_admin;
GRANT USAGE, SELECT ON SEQUENCE tasks_id_seq TO family_admin;