CREATE TABLE IF NOT EXISTS tasks (
  id SERIAL PRIMARY KEY,
  event_id INTEGER REFERENCES events(id) ON DELETE CASCADE,
  assigned_to INTEGER REFERENCES users(id) ON DELETE CASCADE,
  title VARCHAR(200) NOT NULL,
  position VARCHAR(20) DEFAULT 'full',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);